- name: Build with dotnet
  working-directory: MyDotNetApplication
  run: dotnet build MyDotNetApplication.csproj --configuration Release

- name: dotnet publish
  working-directory: MyDotNetApplication
  run: dotnet publish MyDotNetApplication.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"
